version: "3"
networks:
  default:
    name: tp_final_network
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: "zipkin"
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.7.2-management
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo-serie:
    image: mongo
    container_name: "mongo-serie"
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    ports:
      - "27017:27017"
  mongo-catalog:
    image: mongo
    container_name: "mongo-catalog"
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    ports:
      - "27018:27017"
  mysqldb:
    image: mysql:8.0
    container_name: "mysqldb"
    restart: always
    environment:
      - MYSQL_DATABASE=Movie
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - '3306:3306'
  eureka-service:
    image: eureka-service
    container_name: "eureka-service"
    ports:
      - "8761:8761"
    restart: always
  config-service:
    image: config-service
    container_name: "config-service"
    ports:
      - "8888:8888"
    restart: always
  movie-service:
    image: movie-service
    container_name: "movie-service"
    ports:
      - "8082:8082"
    restart: always
  serie-service:
    image: serie-service
    container_name: "serie-service"
    ports:
      - "8084:8084"
    restart: always
  catalog-service:
    image: catalog-service
    container_name: "catalog-service"
    ports:
      - "8086:8086"
    restart: always
  gateway-service:
    image: gateway-service
    container_name: "gateway-service"
    ports:
      - "8080:8080"
    restart: always