server:
  port: 8082

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
  datasource:
    url: jdbc:mysql://mysqldb:3306/Movie
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:data-mysql.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

queue:
  movie:
    name: Movie

info:
  app:
    name: ${spring.application.name}
    description: Movie Service created for Final
    version: 2.0.0
