server:
  port: 8084

spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: final_series
      port: 27017 #El puerto privado de nuestro contenedor de Docker, no el publico
      host: mongo-serie

queue:
  serie:
    name: Serie

info:
  app:
    name: ${spring.application.name}
    description: Serie Service created for Final
    version: 1.0.0
